vanniktech/lint-rules

- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/IssueRegistry.java
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2MethodCheckReturnValueDetector.java
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/Utils.java
- lint-rules-rxjava2-lint/src/test/java/com/vanniktech/lintrules/rxjava2/RxJava2DetectorTest.java
- lint-rules-rxjava2-lint/src/test/java/com/vanniktech/lintrules/rxjava2/RxJava2MethodCheckReturnValueDetectorTest.java
- lint-rules-rxjava2-lint/src/test/java/com/vanniktech/lintrules/rxjava2/RxJavaLintDetectorTest.java
> Add CheckReturnValue Lint Check

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/IssueRegistry.java
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/WrongViewIdFormatDetector.java
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AndroidDetectorTest.java
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/IssueRegistryTest.java
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/WrongViewIdFormatDetectorTest.java
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/IssueRegistry.java
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2MethodCheckReturnValueDetector.java
- lint-rules-rxjava2-lint/src/test/java/com/vanniktech/lintrules/rxjava2/IssueRegistryTest.java
- lint-rules-rxjava2-lint/src/test/java/com/vanniktech/lintrules/rxjava2/RxJava2MethodCheckReturnValueDetectorTest.java
> WrongIdFormatDetector

- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2MissingCompositeDisposableClearDetector.java
- lint-rules-rxjava2-lint/src/test/java/com/vanniktech/lintrules/rxjava2/RxJava2MissingCompositeDisposableClearDetectorTest.java
- lint-rules-rxjava2-lint/src/test/java/com/vanniktech/lintrules/rxjava2/RxJavaLintDetectorTest.java
> CompositeDisposable missing clear() check.

- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/Utils.java
- lint-rules-rxjava2-lint/src/test/java/com/vanniktech/lintrules/rxjava2/RxJava2MethodCheckReturnValueDetectorTest.java
- lint-rules-rxjava2-lint/src/test/java/com/vanniktech/lintrules/rxjava2/RxJavaLintDetectorTest.java
> MethodMissingCheckReturnValue add TestObserver and TestSubscriber.

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/RawColorDetector.java
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/RawColorDetectorTest.java
> RawColor: Ignore tools.

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/RawDimenDetector.java
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/RawDimenDetectorTest.java
> RawDimen: Ignore tools.

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/IssueRegistry.java
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/SuperfluousMarginDeclarationDetector.java
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/SuperfluousPaddingDeclarationDetector.java
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/IssueRegistryTest.java
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/SuperfluousMarginDeclarationDetectorTest.java
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/SuperfluousPaddingDeclarationDetectorTest.java
> Add SuperfluousMarginDeclarationDetector & SuperfluousPaddingDeclarationDetector.

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/AndroidDetector.java
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2Detector.java
> Fix fullyQualifiedMethodName usages show that they show up in the IDE.

- code_quality_tools/detekt.yml
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/IssueRegistry.kt
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2SchedulerCallDetector.kt
- lint-rules-rxjava2-lint/src/test/java/com/vanniktech/lintrules/rxjava2/RxJava2SchedulerCallDetectorTest.kt
- lint-rules-rxjava2-lint/src/test/java/com/vanniktech/lintrules/rxjava2/stubs.kt
> Add RxJava2SchedulerCallDetector.

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/InvalidImportDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/IssueRegistry.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/InvalidImportDetectorTest.kt
> Add InvalidImportDetector.

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/SuperfluousNameSpaceDetector.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/SuperfluousNameSpaceDetectorTest.kt
> SuperfluousNameSpaceDetector: Add quickfix.

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/XmlSpacingDetector.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/XmlSpacingDetectorTest.kt
> XmlSpacingDetector: Add quickfix.

- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2MissingCompositeDisposableClearDetector.java
- lint-rules-rxjava2-lint/src/test/java/com/vanniktech/lintrules/rxjava2/RxJava2MissingCompositeDisposableClearDetectorTest.kt
> Issue #152 Missing recursive composite disposible checks

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/ElementCollectReporter.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/RawColorDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/RawDimenDetector.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/RawColorDetectorTest.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/RawDimenDetectorTest.kt
> RawDimenDetector & RawColorDetector: Add quickfixes.

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/IssueRegistry.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/RawColorDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/RawDimenDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/SuperfluousNameSpaceDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/UnusedMergeAttributesDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/extensions.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/IssueRegistryTest.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/UnusedMergeAttributesDetectorTest.kt
> Add UnusedMergeAttributesDetector.

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/IssueRegistry.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/TodoDetector.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/IssueRegistryTest.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/RawColorDetectorTest.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/TodoDetectorTest.kt
> Add TodoDetector.

- README.md
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/IgnoreWithoutReason.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/IssueRegistry.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/IgnoreWithoutReasonTest.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/IssueRegistryTest.kt
Here, you go! :)
Adds custom lint checks that verifies whether a reason is set on ignored test, or not.
https://groups.google.com/forum/?forum/lint-dev#!topic/lint-dev/RSuG2evl4QM
> Add IgnoreWithoutReason check for Tests

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/ColorCasingDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/IssueRegistry.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/ColorCasingDetectorTest.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/IssueRegistryTest.kt
> Add ColorCasingDetector.

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/AssertjDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/ColorCasingDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/ConstraintLayoutToolsEditorAttributeDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/DefaultLayoutAttributeDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/InvalidSingleLineCommentDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/InvalidStringDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/JcenterDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/LayoutFileNameMatchesClassDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/MissingXmlHeaderDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/UnsupportedLayoutAttributeDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/UnusedMergeAttributesDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/WrongConstraintLayoutUsageDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/WrongMenuIdFormatDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/WrongTestMethodNameDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/WrongViewIdFormatDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/XmlSpacingDetector.kt
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2DisposableDisposeCallDetector.kt
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2MethodMissingCheckReturnValueDetector.kt
Fixes #251. Requires #250 to be merged first.
> Mark applicable quickFixes as auto fixable.

- build.gradle
Currently fails due to https://issuetracker.google.com/issues/119210743
> Update Lint to 26.3.0-rc03

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/AlertDialogUsageDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/AndroidDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/AnnotationOrderDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/AssertjDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/ConstraintLayoutToolsEditorAttributeDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/InvalidImportDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/InvalidSingleLineCommentDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/NamingPatternDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/ShouldUseStaticImportDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/TodoDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/UnsupportedLayoutAttributeDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/WrongTestMethodNameDetector.kt
- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/XmlSpacingDetector.kt
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2DefaultSchedulerDetector.kt
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2DisposableAddAllCallDetector.kt
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2DisposableDisposeCallDetector.kt
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2MethodMissingCheckReturnValueDetector.kt
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2MissingCompositeDisposableClearDetector.kt
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2SchedulersFactoryCallDetector.kt
- lint-rules-rxjava2-lint/src/main/java/com/vanniktech/lintrules/rxjava2/RxJava2SubscribeMissingOnErrorDetector.kt
> Adjust the scope of all Detectors.

- lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/ErroneousLayoutAttributeDetector.kt
- lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/ErroneousLayoutAttributeDetectorTest.kt
> ErroneousLayoutAttributeDetector: Fix false positive with layout_gravity.
